### ISSUE TITLE
eon use ion visionipc, not init copy_q, need to manually init it

### ISSUE THREAD

**Issue by likegogogo** [RetroPilot/retropilot#3]
### Describe the bug
https://github.com/RetroPilot/retropilot/blob/2b089c862fd0a655c972d379c3ff3441fa6a9120/selfdrive/camerad/cameras/camera_common.cc#L129

fix like this:
  int cl_err;
  //std::cout << "frame_size: " << frame_size << ", frame_buf_count: " << frame_buf_count << std::endl;
  for (int i = 0; i < frame_buf_count; i++) {
    camera_bufs[i].allocate(frame_size);

    //TODO only need for visionbuf ion type!!
    camera_bufs[i].copy_q = clCreateCommandQueue(context, device_id, 0, &cl_err);
    assert(cl_err == 0);

    camera_bufs[i].init_cl(device_id, context);
  }

### What hardware does this issue affect?

comma two

### Provide a route where the issue occurs

no_route

### openpilot version

0.8.13

**Comment by wocsor** [comment]
is this a fix for the camerad segfault on Pixel3 or is this a fix for Comma 2 compatibility?

**Comment by likegogogo** [comment]
it may help you solve the camerad segfault problem. But I'm not sure. Now I am busy with a project of our company. May be two week later I will have time. Then I can help solve some problems of retropilot.

By the way, thanks very much for your great work in the Retropilot project.
